### ISSUE TITLE
More globbing support for #PNGImages

### ISSUE THREAD

**Issue by runer112** [PeterTillema/Age-Of-CEmpires-I#10]
Being able to include `*` anywhere in the pattern to include would allow things like [this](https://github.com/PeterTillema/Age-Of-CEmpires-I/blob/afca86035eec805c7b5d4a0476265e07e1ede947/gfx/convpng.ini#L187) to be greatly simplified.

**Comment by mateoconlechuga** [comment]
Why is this issue here.

**Comment by mateoconlechuga** [comment]
Anyway closed with [04f4e0f](https://github.com/mateoconlechuga/convpng/commit/04f4e0f842d2469cfc2f1e98a2ac7dc5550b372c).
