### ISSUE TITLE
weird stuff... do the following:

### ISSUE THREAD

**Issue by SanjivanM** [PeterTillema/Age-Of-CEmpires-I#25]
1. run aoce to install
2. run the app
3. exit
4. I pressed [y=] and got an "ERROR:MEMORY"
5. Check RAM (I had ~150KB)
6. Go to mem mgmt, [2nd][+][2][1]
7. scroll down the list, after OS lists, there is an object called "While".  Try to delete it
8. you get a "ERROR:BAD ADDRESS"
![aoce_error](https://user-images.githubusercontent.com/33943333/43351425-96f10b3e-91c6-11e8-802b-7844b9333673.png)

**Note: I tried this with Cesium installed too, same thing happened

**Comment by LAX18** [comment]
You are aware that AOCE is in development and is not a finished application, correct? Just thought I would mention that @SanjivanM

**Comment by PeterTillema** [comment]
Lol.

**Comment by SanjivanM** [comment]
Yeah, i know... just pointing it out though...  I could put this on a "friend's" calc and watch them react to the error :P
